name: Node.js CI

on:
  release:
    types: [ published ] # otherwise triggers on all release event types
    branches: [ main ]
  pull_request:
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 14.x
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - run: npm ci
  package:
      needs: [ build ]
      runs-on: ubuntu-18.04
      if: github.head_ref != 'main' && github.event_name == 'pull_request'
      steps:
        - name: Get current date
          id: date
          run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
        - uses: actions/checkout@v2
        - name: Use Node.js 14.x
          uses: actions/setup-node@v1
          with:
            node-version: 14.x
        - run: echo ${{ github.payload.pull_request.head.ref }}
        - run: npm ci
        - run: npm version prerelease --preid=pre-release-${{ steps.date.outputs.date }} --no-git-tag-version # makes a pre-release
        - run: npm pack
        - name: Upload
          uses: actions/upload-artifact@v2
          with:
              name: package
              path: "*.tgz"
  publish:
    name: "Publish to GitHub Packages"
    needs: [ package ]
    runs-on: ubuntu-18.04
    if: github.repository_owner == 'fjordskii'
    steps:
    - name: Upload
      uses: actions/download-artifact@v2
      with:
          name: package
    - uses: actions/setup-node@v1
      with:
        node-version: 14.x
        registry-url: https://npm.pkg.github.com/
        scope: "@fjordskii" # important for github package use, forces scope
    - run: echo "registry=https://npm.pkg.github.com/@fjordskii" >> .npmrc
    - run: npm publish $(ls *.tgz)
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }} # magic github repo secret auto-gen'd at runtime