name: Node.js CI

if: ${{ github.ref == 'refs/heads/main' }}
on:
  release:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 14.x
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - run: npm ci
  package:
      needs: [build]
      runs-on: ubuntu-18.04
      steps:
        - uses: actions/checkout@v2
        - name: Use Node.js 14.x
          uses: actions/setup-node@v1
          with:
            node-version: 14.x
        
        - run: npm ci
        # this is the magic github context object, maybe grab branch name instead?
        - run: npm version prerelease --preid=ci-$GITHUB_RUN_ID --no-git-tag-version
        #- run: npm version prerelease --preid=ci-${{ github.ref }} --no-git-tag-version
        - run: npm pack
        - name: Upload
          uses: actions/upload-artifact@v2
          with:
              name: package
              path: "*.tgz"
  publish:
    name: "Publish to GitHub Packages"
    needs: [package]
    runs-on: ubuntu-18.04
    if: github.repository_owner == 'fjordskii'
    steps:
    - name: Upload
      uses: actions/download-artifact@v2
      with:
          name: package
    - uses: actions/setup-node@v1
      with:
        node-version: 14.x
        registry-url: https://npm.pkg.github.com/
        scope: "@fjordskii"
    - run: echo "registry=https://npm.pkg.github.com/@fjordskii" >> .npmrc
    - run: npm publish $(ls *.tgz)
      env:
        NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
if: github.ref != 'refs/heads/main' 
on: 
  pull_request:
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 14.x
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - run: npm ci
  package:
      needs: [build]
      runs-on: ubuntu-18.04
      steps:
        - uses: actions/checkout@v2
        - name: Use Node.js 14.x
          uses: actions/setup-node@v1
          with:
            node-version: 14.x
        
        - run: npm ci
        # this is the magic github context object, maybe grab branch name instead?
        - run: npm version prerelease --preid=ci-$GITHUB_RUN_ID --no-git-tag-version
        #- run: npm version prerelease --preid=ci-${{ github.ref }} --no-git-tag-version
        - run: npm pack
        - name: Upload
          uses: actions/upload-artifact@v2
          with:
              name: package
              path: "*.tgz"
  publish:
    name: "Publish to GitHub Packages"
    needs: [package]
    runs-on: ubuntu-18.04
    if: github.repository_owner == 'fjordskii'
    steps:
    - name: Upload
      uses: actions/download-artifact@v2
      with:
          name: package
    - uses: actions/setup-node@v1
      with:
        node-version: 14.x
        registry-url: https://npm.pkg.github.com/
        scope: "@fjordskii"
    - run: echo "registry=https://npm.pkg.github.com/@fjordskii" >> .npmrc
    - run: npm publish $(ls *.tgz)
      env:
        NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}